USE [WU_I2]
GO

/****** Object:  Table [dbo].[ACCESS_LOG]    Script Date: 5/3/2023 4:19:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AHRQ_WPE_ACCESS_LOG](
	[ACCESS_INSTANT] [numeric](16, 6) NOT NULL,
	[PROCESS_ID] [varchar](254) NOT NULL,
	[ACCESS_TIME] [datetime] NOT NULL,
	[METRIC_ID] [numeric](18, 0) NULL,
	[USER_ID] [varchar](18) NULL,
	--[WORKSTATION_ID] [varchar](254) NULL,
	[PAT_ID] [varchar](18) NULL,
	[CSN] [numeric](18, 0) NULL,
	[ACCESS_ACTION_C] [int] NULL,
	--[DEPLOYMENT_ID] [varchar](25) NULL,
	--[AUDIT_SESSION_ID] [varchar](254) NULL,
 CONSTRAINT [PK_AHRQ_WPE_ACCESS_LOG] PRIMARY KEY CLUSTERED 
(
	[ACCESS_TIME] ASC,
	[PROCESS_ID] ASC,
	[ACCESS_INSTANT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 85, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO